/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as CancelarRouteImport } from './routes/cancelar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AgendarRoomIdRouteImport } from './routes/agendar.$roomId'
import { Route as AdminSalasRouteImport } from './routes/admin/salas'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAdministradoresRouteImport } from './routes/admin/administradores'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelarRoute = CancelarRouteImport.update({
  id: '/cancelar',
  path: '/cancelar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AgendarRoomIdRoute = AgendarRoomIdRouteImport.update({
  id: '/agendar/$roomId',
  path: '/agendar/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalasRoute = AdminSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancelar': typeof CancelarRoute
  '/sucesso': typeof SucessoRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/salas': typeof AdminSalasRoute
  '/agendar/$roomId': typeof AgendarRoomIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancelar': typeof CancelarRoute
  '/sucesso': typeof SucessoRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/salas': typeof AdminSalasRoute
  '/agendar/$roomId': typeof AgendarRoomIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancelar': typeof CancelarRoute
  '/sucesso': typeof SucessoRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/salas': typeof AdminSalasRoute
  '/agendar/$roomId': typeof AgendarRoomIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cancelar'
    | '/sucesso'
    | '/admin/administradores'
    | '/admin/login'
    | '/admin/salas'
    | '/agendar/$roomId'
    | '/admin/'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancelar'
    | '/sucesso'
    | '/admin/administradores'
    | '/admin/login'
    | '/admin/salas'
    | '/agendar/$roomId'
    | '/admin'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cancelar'
    | '/sucesso'
    | '/admin/administradores'
    | '/admin/login'
    | '/admin/salas'
    | '/agendar/$roomId'
    | '/admin/'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CancelarRoute: typeof CancelarRoute
  SucessoRoute: typeof SucessoRoute
  AgendarRoomIdRoute: typeof AgendarRoomIdRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelar': {
      id: '/cancelar'
      path: '/cancelar'
      fullPath: '/cancelar'
      preLoaderRoute: typeof CancelarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agendar/$roomId': {
      id: '/agendar/$roomId'
      path: '/agendar/$roomId'
      fullPath: '/agendar/$roomId'
      preLoaderRoute: typeof AgendarRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/salas': {
      id: '/admin/salas'
      path: '/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AdminSalasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSalasRoute: typeof AdminSalasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSalasRoute: AdminSalasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CancelarRoute: CancelarRoute,
  SucessoRoute: SucessoRoute,
  AgendarRoomIdRoute: AgendarRoomIdRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
